camera:
  ae_constraint_mode: 0
  ae_exposure_mode: 0
  ae_metering_mode: 1
  af_mode: 0
  af_range: 0
  af_speed: 0
  analogue_gain: 0.0
  awb_mode: 0
  brightness: 0.2
  colour_gain_blue: 1.0
  colour_gain_red: 1.0
  contrast: 1.6
  exposure_time: 0
  exposure_value: 0.0
  flicker_avoidance_hz: 0
  hdr: false
  hflip: false
  lens_position: 5.8
  max_exposure_us: 67333
  night_vision: true
  noise_reduction_mode: 1
  saturation: 1.2
  sharpness: 1.0
  vflip: false
live:
  framerate: 15
  jpeg_quality: 85
  resolution:
  - 1280
  - 720
  watchdog_seconds: 180
pir:
  gpio_pin: 17
  min_pulse_ms: 200.0
  pull_down: true
  pulse_count: 4
  pulse_window_min_ms: 45.0
  pulse_window_s: 1.2
power_saving:
  bluetooth_off: true
  hdmi_off: true
  leds_off: true
relay:
  active_high: true
  gpio_pin: 18
server:
  host: 0.0.0.0
  port: 8080
  users:
  - password_hash: $2b$12$NW0VBcuNOQFp.Bl7F55ELuN2iWBoVdsbdS05X5aoOveCuzbXmVcuC
    role: admin
    username: admin
  - password_hash: $2b$12$6o/f6zQJNSBE3bKmRGbKNO7e5cNDiuftbNmQUn5HfA3rjAMajXKIi
    role: user
    username: Claudi
  - password_hash: $2b$12$/He.kegMY8n0qbx3Vhw3Kuiuq0Enhu0ynONAd6SD/Glr9j.tkPWqG
    role: admin
    username: Stefan
storage:
  halt_free_mb: 100
  min_free_mb: 500
  nas:
    enabled: true
    password: '101101'
    remote_path: /wildlife/
    server: 192.168.10.99
    share: JDownloads
    username: root
  recordings_path: /recordings
trap:
  enabled: true
  framerate: 30
  post_event_seconds: 8
  pre_event_seconds: 2
  resolution:
  - 1920
  - 1080
